# Generated by Django 5.2.11 on 2026-02-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='API endpoint')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бизнес-элемент',
                'verbose_name_plural': 'Бизнес-элементы',
                'db_table': 'business_elements',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField(default=False, verbose_name='Чтение своих')),
                ('read_all_permission', models.BooleanField(default=False, verbose_name='Чтение всех')),
                ('create_permission', models.BooleanField(default=False, verbose_name='Создание')),
                ('update_permission', models.BooleanField(default=False, verbose_name='Изменение своих')),
                ('update_all_permission', models.BooleanField(default=False, verbose_name='Изменение всех')),
                ('delete_permission', models.BooleanField(default=False, verbose_name='Удаление своих')),
                ('delete_all_permission', models.BooleanField(default=False, verbose_name='Удаление всех')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.businesselement', verbose_name='Элемент')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.role', verbose_name='Роль')),
            ],
            options={
                'db_table': 'access_rules',
                'unique_together': {('role', 'element')},
            },
        ),
    ]
